apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- rbac.yaml
- credentials.yaml
- backup-pvc.yaml
- networkpolicy.yaml

configMapGenerator:
- name: services-dashboard-html
  files:
  - index.html
  - backups.html
- name: services-dashboard-scripts
  files:
  - services.sh
- name: services-dashboard-nginx
  files:
  - nginx.conf
