apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: staging

namespace: staging

resources:
- ../../walkthrough/step-4


configMapGenerator:
- behavior: merge
  envs:
  - config/common.env
  name: config
patches:
- path: patches/magento-web.yaml
- path: patches/magento-consumer.yaml
- path: patches/ingress.yaml
