apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main
spec:
  rules:
  - host: magento.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnish
            port:
              name: http
  tls:
  - hosts:
    - magento.example.com
    secretName: magento-production
