env:
  - name: ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password

config:
  outputs: |
    [OUTPUT]
        Name  es
        Match *
        Host  elasticsearch-master
        Port  9200
        Logstash_Format On
        Suppress_Type_Name On
        Replace_Dots On
        tls On
        tls.verify Off
        HTTP_User elastic
        HTTP_Passwd ${ES_PASSWORD}
        Retry_Limit False
