apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../../walkthrough/step-1

patchesStrategicMerge:
- patches/ingress-direct.yaml
- patches/magento-web.yaml

configMapGenerator:
- name: config
  behavior: merge
  envs:
  - config/common.env
