apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: step-2


resources:
- hpa/magento-web.yaml
- ../step-1
- ../../bases/redis


configMapGenerator:
- behavior: merge
  envs:
  - config/additional.env
  name: additional
patches:
- path: patches/wait-for-redis.yaml
