apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
- ../../../walkthrough/step-1


configMapGenerator:
- behavior: merge
  envs:
  - config/common.env
  name: config
patches:
- path: patches/ingress-direct.yaml
- path: patches/magento-web.yaml
