apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-web
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: magento-web
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
