apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 12Gi
    limits.cpu: "10"
    limits.memory: 20Gi
    count/pods: "40"
    count/services: "20"
    count/configmaps: "30"
    count/secrets: "30"
    count/persistentvolumeclaims: "10"
    requests.storage: 30Gi
