apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
- ../../../walkthrough/step-3

patchesStrategicMerge:
- patches/ingress.yaml
- patches/magento-web.yaml

configMapGenerator:
- name: config
  behavior: merge
  envs:
  - config/common.env
